# Learn transformers from scratch

In [137]:
# self attention

# Query : what am i looking for

# Key : what information do i contain?

# Value : What information should i actually provide? 

# Q = X * Wq
# K = X * Wk
# V = X * Wv

import torch
import math

torch.manual_seed(42) 

X = torch.tensor([
    [0.2, 0.4, 0.1, 0.7],
    [0.8, 0.1, 0.6, 0.2],
    [0.3, 0.9, 0.2, 0.5],
    [0.7, 0.2, 0.8, 0.1]
])

print(X.shape)

torch.Size([4, 4])


In [138]:
d_model = 4
d_k = 4

W_q = torch.randn(d_model, d_k)
W_k = torch.randn(d_model, d_k)
W_v = torch.randn(d_model, d_k)

print(W_q)
print(W_k)
print(W_v)

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]])
tensor([[ 1.6423, -0.1596, -0.4974,  0.4396],
        [-0.7581,  1.0783,  0.8008,  1.6806],
        [ 1.2791,  1.2964,  0.6105,  1.3347],
        [-0.2316,  0.0418, -0.2516,  0.8599]])
tensor([[-1.3847, -0.8712, -0.2234,  1.7174],
        [ 0.3189, -0.4245,  0.3057, -0.7746],
        [-1.5576,  0.9956, -0.8798, -0.6011],
        [-1.2742,  2.1228, -1.2347, -0.4879]])


In [139]:
Q = X @ W_q
K = X @ W_k
V = X @ W_v

print(Q)
print('\n')

print(K)
print('\n')

print(V)
print('\n')

tensor([[ 0.0720, -0.4231, -0.4145, -0.6696],
        [ 1.0125,  1.9437,  0.3270, -2.5346],
        [ 0.6743, -0.6149, -0.2315, -1.9754],
        [ 0.8100,  2.0572,  0.2310, -2.8414]])


tensor([[-9.0136e-03,  5.5828e-01,  1.0578e-01,  1.4955e+00],
        [ 1.9592e+00,  7.6636e-01, -1.8731e-03,  1.4925e+00],
        [-4.9610e-02,  1.2028e+00,  5.6781e-01,  2.3413e+00],
        [ 1.9981e+00,  1.1453e+00,  2.7520e-01,  1.7976e+00]])


tensor([[-1.1970,  1.2415, -0.8746, -0.3680],
        [-2.2652,  0.2825, -0.9229,  0.8382],
        [-1.0770,  0.6171, -0.5851, -0.5461],
        [-2.2790,  0.3140, -0.9225,  0.5175]])




In [140]:
scores = Q @ K.T # have to multiply with each other word k value that is why we need it to transpose
print(scores)
print(scores.shape)

tensor([[-1.2821, -1.1818, -2.3156, -1.6584],
        [-2.6799, -0.3103, -3.4609, -0.2170],
        [-3.3281, -2.0980, -5.5294, -2.9715],
        [-3.0838, -1.0778, -4.0873, -1.0696]])
torch.Size([4, 4])


In [141]:
scores = scores/math.sqrt(d_k)
print(scores)

tensor([[-0.6411, -0.5909, -1.1578, -0.8292],
        [-1.3400, -0.1551, -1.7304, -0.1085],
        [-1.6640, -1.0490, -2.7647, -1.4858],
        [-1.5419, -0.5389, -2.0437, -0.5348]])


In [142]:
attention_weights = torch.softmax(scores, dim=-1)
print(attention_weights)

tensor([[0.2877, 0.3025, 0.1716, 0.2383],
        [0.1194, 0.3905, 0.0808, 0.4092],
        [0.2284, 0.4225, 0.0760, 0.2730],
        [0.1415, 0.3857, 0.0856, 0.3872]])


In [143]:
output = attention_weights @ V
print(output)
print(output.shape)

tensor([[-1.7574,  0.6233, -0.8510,  0.1773],
        [-2.0472,  0.4370, -0.8897,  0.4510],
        [-1.9347,  0.5356, -0.8861,  0.3699],
        [-2.0177,  0.4590, -0.8870,  0.4248]])
torch.Size([4, 4])


In [144]:
print(Q)
print(K)

tensor([[ 0.0720, -0.4231, -0.4145, -0.6696],
        [ 1.0125,  1.9437,  0.3270, -2.5346],
        [ 0.6743, -0.6149, -0.2315, -1.9754],
        [ 0.8100,  2.0572,  0.2310, -2.8414]])
tensor([[-9.0136e-03,  5.5828e-01,  1.0578e-01,  1.4955e+00],
        [ 1.9592e+00,  7.6636e-01, -1.8731e-03,  1.4925e+00],
        [-4.9610e-02,  1.2028e+00,  5.6781e-01,  2.3413e+00],
        [ 1.9981e+00,  1.1453e+00,  2.7520e-01,  1.7976e+00]])


In [145]:
print(Q[0])

print(K[0])

scores11 = Q[0] @ K[0]
scores12 = Q[0] @ K[1]
scores13 = Q[0] @ K[2]
scores14 = Q[0] @ K[3]

scores = torch.stack([
    scores11,
    scores12,
    scores13,
    scores14
])

print(scores.shape)

print(scores)

scores = scores/math.sqrt(d_k)

print(scores)

scores = torch.softmax(scores, dim=-1)

print(f"V = {V}")
print(scores)

scores = scores @ V
print("scores after @V")
print(scores)


tensor([ 0.0720, -0.4231, -0.4145, -0.6696])
tensor([-0.0090,  0.5583,  0.1058,  1.4955])
torch.Size([4])
tensor([-1.2821, -1.1818, -2.3156, -1.6584])
tensor([-0.6411, -0.5909, -1.1578, -0.8292])
V = tensor([[-1.1970,  1.2415, -0.8746, -0.3680],
        [-2.2652,  0.2825, -0.9229,  0.8382],
        [-1.0770,  0.6171, -0.5851, -0.5461],
        [-2.2790,  0.3140, -0.9225,  0.5175]])
tensor([0.2877, 0.3025, 0.1716, 0.2383])
scores after @V
tensor([-1.7574,  0.6233, -0.8510,  0.1773])


# multi headed self attention

In [146]:
seq_len = 4
d_model = 8
num_heads = 2

d_k = d_model // num_heads

X = torch.randn(seq_len, d_model)

print(f"x = {X.shape}")
print(f"d_k = {d_k}")

x = torch.Size([4, 8])
d_k = 4


In [147]:
W_Q = torch.randn(d_model, d_model) # d_k before splitting based on head is same as d_model, we progress which is better to make the model learn the parameters
W_K = torch.randn(d_model, d_model)
W_V = torch.randn(d_model, d_model)

Q = X @ W_Q

K = X @ W_K

V = X @ W_V

print(Q.shape)
print(K.shape)
print(V.shape)
print('\n')
print(Q)

torch.Size([4, 8])
torch.Size([4, 8])
torch.Size([4, 8])


tensor([[-2.5090,  0.5599,  5.1385,  1.1498,  2.1700, -0.9508, -0.8187, -1.2652],
        [-0.5434,  0.2169,  1.5733,  4.9437,  0.9145,  0.1673, -1.9814,  0.6744],
        [-6.0908, -0.5521, -1.9110,  2.2170,  0.5591,  1.5691,  3.3131, -0.3604],
        [-5.7809, -2.3053,  3.9936,  2.0768, -0.5484, -4.4979, -1.0524, -1.6200]])


In [148]:
Q = Q.view(seq_len, num_heads, d_k) # 4, 2, 4

print(Q)

Q = Q.transpose(0, 1)

print(Q.shape)

print('\n')

print(Q)


tensor([[[-2.5090,  0.5599,  5.1385,  1.1498],
         [ 2.1700, -0.9508, -0.8187, -1.2652]],

        [[-0.5434,  0.2169,  1.5733,  4.9437],
         [ 0.9145,  0.1673, -1.9814,  0.6744]],

        [[-6.0908, -0.5521, -1.9110,  2.2170],
         [ 0.5591,  1.5691,  3.3131, -0.3604]],

        [[-5.7809, -2.3053,  3.9936,  2.0768],
         [-0.5484, -4.4979, -1.0524, -1.6200]]])
torch.Size([2, 4, 4])


tensor([[[-2.5090,  0.5599,  5.1385,  1.1498],
         [-0.5434,  0.2169,  1.5733,  4.9437],
         [-6.0908, -0.5521, -1.9110,  2.2170],
         [-5.7809, -2.3053,  3.9936,  2.0768]],

        [[ 2.1700, -0.9508, -0.8187, -1.2652],
         [ 0.9145,  0.1673, -1.9814,  0.6744],
         [ 0.5591,  1.5691,  3.3131, -0.3604],
         [-0.5484, -4.4979, -1.0524, -1.6200]]])


In [149]:
K = K.view(seq_len, num_heads, d_k).transpose(0, 1)
V = V.view(seq_len, num_heads, d_k).transpose(0, 1)

print(K.shape)
print(V.shape)

torch.Size([2, 4, 4])
torch.Size([2, 4, 4])


In [150]:
scores = Q @ K.transpose(-2, -1)
print(scores.shape)

torch.Size([2, 4, 4])


In [151]:
scores = scores / math.sqrt(d_k)

attention_weights = torch.softmax(scores, -1)

output = attention_weights @ V

print(output.shape)

W_O = torch.randn(d_model, d_model)

print(W_O)



torch.Size([2, 4, 4])
tensor([[-1.3793,  0.6258, -2.5850, -0.0240, -0.1222, -0.7470,  1.7093,  0.0579],
        [ 1.1930,  1.9373,  0.7287,  0.9809,  0.4146,  1.1566,  0.2691, -0.0366],
        [ 0.9733, -1.0151, -0.5419, -0.4410, -0.3136, -0.1293, -0.7150, -0.0476],
        [ 2.0207,  0.2539,  0.9364,  0.7122, -0.0318,  0.1016,  1.3433,  0.7133],
        [ 0.4038, -0.7140,  0.8337, -0.9585,  0.4536,  1.2461, -2.3065, -1.2869],
        [ 0.1799, -2.1268, -0.1341, -1.0408, -0.7647, -0.0553,  1.2049, -0.9825],
        [ 0.4334, -0.7172,  1.0554, -1.4534,  0.4652,  0.3714, -0.0047,  0.0795],
        [ 0.3782,  0.7051, -1.7237, -0.8435,  0.4351,  0.2659, -0.5871,  0.0827]])


In [152]:
head_outputs = output.transpose(0, 1)

print(head_outputs.shape)

head_output = head_outputs.reshape(seq_len, d_model) # 4, 8

print(head_output.shape)

print(W_O.shape)

output = head_output @ W_O

print(output.shape)

torch.Size([4, 2, 4])
torch.Size([4, 8])
torch.Size([8, 8])
torch.Size([4, 8])


# Trainable pytorch Layer

In [153]:
import torch.nn as nn

class MultiHeadAttention(nn.Module):
    """Class for multi head attention layer for transfomers"""

    def __init__(self, d_model, num_heads):

        super().__init__()

        self.model = d_model
        self.num_heads = num_heads

        self.d_k = int(self.model/self.num_heads)

        self.W_Q = nn.Parameter(
            torch.randn(d_model, d_model) # don't want to consider d_k yet as there will head split for attention
        )

        self.W_K = nn.Parameter(
            torch.randn(d_model, d_model)
        )

        self.W_V = nn.Parameter(
            torch.randn(d_model, d_model)
        )

        self.W_O = nn.Parameter(
            torch.randn(d_model, d_model)
        )

    def forward(self, X):
        Q = X @ self.W_Q
        K = X @ self.W_K
        V = X @ self.W_V

        Q = Q.reshape(-1, self.num_heads, self.d_k).transpose(0,1) # -1 calcualtes dimention automatically based on remaining dimensions
        K = K.reshape(-1, self.num_heads, self.d_k).transpose(0,1)
        V = V.reshape(-1, self.num_heads, self.d_k).transpose(0,1)

        scores = Q @ K.transpose(-2, -1)
        scores = scores/math.sqrt(self.d_k)
        attention_weights = torch.softmax(scores, dim=-1)

        heads_output = attention_weights @ V  # heads output shape = (2, 4, 4) 

        print(heads_output.shape)
        heads_output = heads_output.transpose(0, 1) # it became 4, 2, 4

        head_output = heads_output.reshape(-1, self.model) # 4, 8 -> combined two heads here

        output = head_output @ self.W_O

        return output        


In [154]:
X = torch.randn(4, 8)

attention = MultiHeadAttention(
    d_model = 8,
    num_heads = 2
)

output = attention(X)

print(X.shape)
print(output.shape)

torch.Size([2, 4, 4])
torch.Size([4, 8])
torch.Size([4, 8])


In [155]:
for name, parameter in attention.named_parameters():
    print(name, parameter.requires_grad, parameter.shape)

W_Q True torch.Size([8, 8])
W_K True torch.Size([8, 8])
W_V True torch.Size([8, 8])
W_O True torch.Size([8, 8])


In [156]:
loss = output.sum()
loss.backward()
print(attention.W_Q.grad)
print(loss)

tensor([[  5.0704,  -0.5216,   1.9874,   7.7179,  -2.1232,   1.2201,  -8.2259,
          -6.3307],
        [  3.3997,  -3.6020,   3.6967,   1.8830,   0.3223,  -2.8885,  14.6450,
           8.0787],
        [  3.1493,  -0.6499,   1.4494,   4.4196,  -0.7512,  -3.4810,  14.4796,
           7.3136],
        [  0.8008,   0.3340,   0.0685,   1.7561,  -1.7498,   7.1847, -35.5505,
         -20.7945],
        [  2.6106,  -1.3955,   1.8678,   2.8841,  -1.1397,  -0.5292,  -0.3151,
          -0.9423],
        [ -4.0854,   3.1679,  -3.5640,  -3.3676,  -0.4161,   7.5370, -35.2921,
         -19.5256],
        [ -2.8888,   2.3028,  -2.5698,  -2.3257,  -0.2410,   5.0296, -23.4656,
         -12.9581],
        [  0.8570,  -2.9449,   2.3337,  -1.7462,   2.8409, -11.3866,  57.3864,
          33.4205]])
tensor(-30.0765, grad_fn=<SumBackward0>)


In [157]:
import torch.nn as nn

class MultiHeadAttention(nn.Module):
    """Class for multi head attention layer for transfomers with batch size"""

    def __init__(self, d_model, num_heads):

        super().__init__()

        self.model = d_model
        self.num_heads = num_heads

        self.d_k = int(self.model/self.num_heads)

        self.W_Q = nn.Parameter(
            torch.randn(d_model, d_model) # don't want to consider d_k yet as there will head split for attention
        )

        self.W_K = nn.Parameter(
            torch.randn(d_model, d_model)
        )

        self.W_V = nn.Parameter(
            torch.randn(d_model, d_model)
        )

        self.W_O = nn.Parameter(
            torch.randn(d_model, d_model)
        )

    def forward(self, X):
        """ forward actual code"""
        Q = X @ self.W_Q
        K = X @ self.W_K
        V = X @ self.W_V

        Q = Q.reshape(-1, self.num_heads, self.d_k).transpose(0,1) # -1 calcualtes dimention automatically based on remaining dimensions
        K = K.reshape(-1, self.num_heads, self.d_k).transpose(0,1) # 4, 2, 4, after transpose it becomes 2, 4, 4
        V = V.reshape(-1, self.num_heads, self.d_k).transpose(0,1)

        scores = Q @ K.transpose(-2, -1)
        scores = scores/math.sqrt(self.d_k)
        attention_weights = torch.softmax(scores, dim=-1)

        heads_output = attention_weights @ V  # heads output shape = (2, 4, 4) 

        print(heads_output.shape)
        heads_output = heads_output.transpose(0, 1) # it became 4, 2, 4

        head_output = heads_output.reshape(-1, self.model) # 4, 8 -> combined two heads here

        output = head_output @ self.W_O

        return output        


In [158]:
torch.manual_seed(42)

X = torch.randn(4, 8)

attention = MultiHeadAttention(
    d_model = 8,
    num_heads = 2
)

output = attention(X)

print(f"Input: {X.shape}")
print(f"Output: {output.shape}")

torch.Size([2, 4, 4])
Input: torch.Size([4, 8])
Output: torch.Size([4, 8])


In [159]:
for name, parameter in attention.named_parameters():
    print(
        name,
        parameter.shape,
        parameter.requires_grad # if this is true, pytorch will track grdients for the parameters
    )

W_Q torch.Size([8, 8]) True
W_K torch.Size([8, 8]) True
W_V torch.Size([8, 8]) True
W_O torch.Size([8, 8]) True


In [160]:
loss = output.sum()
loss.backward()
print(attention.W_Q.grad)

tensor([[-1.2850e+00,  4.1542e-01,  1.4861e-02, -2.9348e-02, -2.2599e+01,
         -1.6663e+01, -1.8253e+01, -2.9351e+01],
        [ 4.1887e+00, -9.5913e-02, -1.6363e+00,  3.2538e+00, -5.7739e+00,
         -8.0836e+00, -6.2708e+00, -2.9562e+01],
        [-6.5742e-01,  2.2680e-01,  7.8706e-02,  1.9899e-01,  3.1025e+00,
          4.4290e-01,  1.7251e+00, -6.6462e+00],
        [-3.9461e+00, -1.5422e-01,  1.4334e+00, -4.5131e+00, -9.1373e+00,
         -8.2871e+00, -8.0390e+00, -2.0856e+01],
        [-1.4477e+00,  2.8546e-01,  4.3558e-01, -1.1435e-01,  1.0001e+01,
          7.1270e+00,  7.9693e+00,  1.1530e+01],
        [-1.6920e+00, -1.3367e-01,  6.5617e-01, -2.1919e+00, -1.1241e+01,
         -6.5388e+00, -8.3414e+00, -4.4947e+00],
        [-1.8014e+00,  1.3465e-01,  5.7570e-01, -1.1852e+00, -6.7205e+00,
         -2.8753e+00, -4.5526e+00,  3.2773e+00],
        [ 1.1946e+00, -4.9622e-01, -3.2200e-01, -1.1429e+00, -2.2786e+01,
         -1.6583e+01, -1.8306e+01, -2.8291e+01]])


# self attention with batch mode enabled

In [161]:
import torch
import torch.nn as nn
import math

class MultiHeadAttention(nn.Module):

    def __init__(self, d_model, num_heads):
        super().__init__()

        assert d_model % num_heads == 0

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = self.d_model // self.num_heads

        self.W_Q = nn.Parameter(torch.randn(d_model, d_model))
        self.W_K = nn.Parameter(torch.randn(d_model, d_model))
        self.W_V = nn.Parameter(torch.randn(d_model, d_model))
        self.W_O = nn.Parameter(torch.randn(d_model, d_model))

    def forward(self, X):

        batch_size, seq_len, token_len = X.shape

        Q = X @ self.W_Q
        K = X @ self.W_K
        V = X @ self.W_V


        Q = Q.reshape(batch_size, seq_len, self.num_heads, self.d_k)

        K = K.reshape(batch_size, seq_len, self.num_heads, self.d_k)

        V = V.reshape(batch_size, seq_len, self.num_heads, self.d_k)

        Q = Q.transpose(1, 2)

        V = V.transpose(1, 2)

        K = K.transpose(1, 2)


        scores = Q @ K.transpose(-2, -1)

        scores = scores/math.sqrt(d_k)

        attention_scores = torch.softmax(scores, dim=-1)

        head_output = attention_scores @ V

        head_output.transpose(1, 2)

        head_output = head_output.reshape(batch_size, seq_len, self.d_model)

        output = head_output @ self.W_O

        return output


In [162]:
torch.manual_seed(42)

X = torch.randn(3, 4, 8)

attention = MultiHeadAttention(d_model=8, num_heads = 2)

output = attention(X)

print(X.shape)
print(output.shape)

torch.Size([3, 4, 8])
torch.Size([3, 4, 8])


# positional embeddings

In [163]:
class PositionalEncoding():
    def __init__(self, seq_len, d_model):
        self.model = d_model
        self.seq_len = seq_len

        self.position_embeddings = torch.zeros(self.seq_len, self.model)

        positions = torch.arange(0, self.seq_len, dtype=torch.float)
        positions = positions.unsqueeze(1)
        print(positions.shape)


        div_term = torch.exp(
            torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model)
        )

        print(div_term)

        self.position_embeddings[:, 0::2] = torch.sin(positions * div_term)
        self.position_embeddings[:, 1::2] = torch.cos(positions * div_term)

        

In [164]:
test = PositionalEncoding(4, 8)
print(test.position_embeddings[1])


torch.Size([4, 1])
tensor([1.0000e+00, 1.0000e-01, 1.0000e-02, 1.0000e-03])
tensor([0.8415, 0.5403, 0.0998, 0.9950, 0.0100, 0.9999, 0.0010, 1.0000])


In [165]:


class PositionalEncoding(nn.Module):

    def __init__(self, d_model, max_seq_len):

        super().__init__()

        pe = torch.zeros(
            max_seq_len,
            d_model
        )

        position = torch.arange(
            0,
            max_seq_len,
            dtype=torch.float
        ).unsqueeze(1)

        div_term = torch.exp(
            torch.arange(
                0,
                d_model,
                2
            ).float()
            *
            (-math.log(10000.0) / d_model)
        )

        pe[:, 0::2] = torch.sin(
            position * div_term
        )

        pe[:, 1::2] = torch.cos(
            position * div_term
        )

        self.register_buffer(
            "pe",
            pe
        )

    def forward(self, x):

        seq_len = x.size(1)

        return x + self.pe[:seq_len]

In [166]:
class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff):
        super().__init__()

        self.linear1 = nn.Linear(d_model, d_ff)

        self.linear2 = nn.Linear(d_ff, d_model)

        self.relu = nn.ReLU()

    def forward(self, X):
        X = self.linear1(X)
        X = self.relu(X)
        X = self.linear2(X)
        return X
    

# Encoder

In [167]:
class Encoder(nn.Module):
    
    def __init__(self, d_model, num_heads, d_ff):
        super().__init__()

        self.attention = MultiHeadAttention(d_model, num_heads)

        self.feed_forward = FeedForward(d_model, d_ff)

        self.norm1 = nn.LayerNorm(d_model)

        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, X):

        attention_out = self.attention(X)

        X = X + attention_out

        X = self.norm1(X)

        ff_out = self.feed_forward(X)

        X = X + ff_out

        X = self.norm2(X)

        return X

In [168]:
torch.manual_seed(42)

X = torch.randn(3, 4, 8) # batch, sequence len, d_model (no of nums representing tokens)

encoder = Encoder(d_model=8, num_heads=2 , d_ff=32)

output = encoder(X)

print(X.shape)
print(output.shape)

torch.Size([3, 4, 8])
torch.Size([3, 4, 8])


# Full Encoder

In [169]:

class TransformerEncoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        d_model,
        num_heads,
        d_ff,
        max_seq_len
    ):

        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            d_model
        )

        self.positional_encoding = (
            PositionalEncoding(
                d_model,
                max_seq_len
            )
        )

        self.encoder = Encoder(
            d_model,
            num_heads,
            d_ff
        )

    def forward(self, token_ids):

        # Token IDs → embeddings
        x = self.embedding(token_ids)

        # Add positional information
        x = self.positional_encoding(x)

        # Transformer encoder block
        x = self.encoder(x)

        return x

In [170]:
torch.manual_seed(42)

vocab_size = 9
d_model = 8
num_heads = 2
d_ff = 32
max_seq_len = 10

model = TransformerEncoder(
    vocab_size=vocab_size,
    d_model=d_model,
    num_heads=num_heads,
    d_ff=d_ff,
    max_seq_len=max_seq_len
)

In [171]:
tokens = torch.tensor([
    [1, 2, 4],
    [1, 3, 5]
])

output = model(tokens)

print(output.shape)

print(output)

torch.Size([2, 3, 8])
tensor([[[ 0.0494,  2.2343, -0.5595, -0.8674,  0.4844, -0.3927,  0.2678,
          -1.2163],
         [ 0.1266, -0.7023,  1.4568,  0.1291, -0.7067,  1.1251,  0.4184,
          -1.8470],
         [-0.6501, -1.0364,  0.2976,  1.6872, -0.0591,  0.2990, -1.5595,
           1.0213]],

        [[ 0.5021,  1.0935,  0.5137,  1.2609, -0.5347, -0.5804, -0.2522,
          -2.0029],
         [ 0.2582, -0.2243, -0.6089, -0.6765,  0.7013,  2.0960, -0.0747,
          -1.4711],
         [-0.9348, -0.1325, -1.0620, -0.6276,  0.5830,  1.4027, -0.8356,
           1.6067]]], grad_fn=<NativeLayerNormBackward0>)


# predictable transformer encoder



In [182]:
values = [
'<PAD>',
'The',
'cat',
'dog',
'sat',
'ran',
'on',
'mat',
'home'
]

In [173]:
class TransformerLanguageModel(nn.Module):

    def __init__(
        self,
        vocab_size,
        d_model,
        num_heads,
        d_ff,
        max_seq_len
    ):

        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            d_model
        )

        self.positional_encoding = (
            PositionalEncoding(
                d_model,
                max_seq_len
            )
        )

        self.encoder = Encoder(
            d_model,
            num_heads,
            d_ff
        )

        self.output_projection = nn.Linear(
            d_model,
            vocab_size
        )


    def forward(self, token_ids):

        # Token IDs → embeddings
        x = self.embedding(token_ids)

        # Add position information
        x = self.positional_encoding(x)

        # Transformer
        x = self.encoder(x)

        # Convert representation → vocabulary logits
        logits = self.output_projection(x)

        return logits

In [174]:
torch.manual_seed(42)

model = TransformerLanguageModel(
    vocab_size=9,
    d_model=8,
    num_heads=2,
    d_ff=32,
    max_seq_len=10
)

tokens = torch.tensor([
    [1, 2, 4],
    [1, 3, 5]
])

logits = model(tokens)

print(logits.shape)

torch.Size([2, 3, 9])


In [183]:
print(values)

['<PAD>', 'The', 'cat', 'dog', 'sat', 'ran', 'on', 'mat', 'home']


In [184]:
print(logits[0, 1])
prediction = torch.argmax(logits[0, 1])
print(prediction.item())
print
print(values[2])

tensor([ 0.1183, -1.5618,  0.8307, -1.0801,  0.7870,  0.0305,  0.3445,  0.1886,
        -0.0099], grad_fn=<SelectBackward0>)
2
cat


# prediction is cat