# Learn transformers from scratch

In [49]:
# self attention

# Query : what am i looking for

# Key : what information do i contain?

# Value : What information should i actually provide? 

# Q = X * Wq
# K = X * Wk
# V = X * Wv

import torch
import math

torch.manual_seed(42) 

X = torch.tensor([
    [0.2, 0.4, 0.1, 0.7],
    [0.8, 0.1, 0.6, 0.2],
    [0.3, 0.9, 0.2, 0.5],
    [0.7, 0.2, 0.8, 0.1]
])

print(X.shape)

torch.Size([4, 4])


In [50]:
d_model = 4
d_k = 4

W_q = torch.randn(d_model, d_k)
W_k = torch.randn(d_model, d_k)
W_v = torch.randn(d_model, d_k)

print(W_q)
print(W_k)
print(W_v)

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]])
tensor([[ 1.6423, -0.1596, -0.4974,  0.4396],
        [-0.7581,  1.0783,  0.8008,  1.6806],
        [ 1.2791,  1.2964,  0.6105,  1.3347],
        [-0.2316,  0.0418, -0.2516,  0.8599]])
tensor([[-1.3847, -0.8712, -0.2234,  1.7174],
        [ 0.3189, -0.4245,  0.3057, -0.7746],
        [-1.5576,  0.9956, -0.8798, -0.6011],
        [-1.2742,  2.1228, -1.2347, -0.4879]])


In [51]:
Q = X @ W_q
K = X @ W_k
V = X @ W_v

print(Q)
print('\n')

print(K)
print('\n')

print(V)
print('\n')

tensor([[ 0.0720, -0.4231, -0.4145, -0.6696],
        [ 1.0125,  1.9437,  0.3270, -2.5346],
        [ 0.6743, -0.6149, -0.2315, -1.9754],
        [ 0.8100,  2.0572,  0.2310, -2.8414]])


tensor([[-9.0136e-03,  5.5828e-01,  1.0578e-01,  1.4955e+00],
        [ 1.9592e+00,  7.6636e-01, -1.8731e-03,  1.4925e+00],
        [-4.9610e-02,  1.2028e+00,  5.6781e-01,  2.3413e+00],
        [ 1.9981e+00,  1.1453e+00,  2.7520e-01,  1.7976e+00]])


tensor([[-1.1970,  1.2415, -0.8746, -0.3680],
        [-2.2652,  0.2825, -0.9229,  0.8382],
        [-1.0770,  0.6171, -0.5851, -0.5461],
        [-2.2790,  0.3140, -0.9225,  0.5175]])




In [52]:
scores = Q @ K.T # have to multiply with each other word k value that is why we need it to transpose
print(scores)
print(scores.shape)

tensor([[-1.2821, -1.1818, -2.3156, -1.6584],
        [-2.6799, -0.3103, -3.4609, -0.2170],
        [-3.3281, -2.0980, -5.5294, -2.9715],
        [-3.0838, -1.0778, -4.0873, -1.0696]])
torch.Size([4, 4])


In [53]:
scores = scores/math.sqrt(d_k)
print(scores)

tensor([[-0.6411, -0.5909, -1.1578, -0.8292],
        [-1.3400, -0.1551, -1.7304, -0.1085],
        [-1.6640, -1.0490, -2.7647, -1.4858],
        [-1.5419, -0.5389, -2.0437, -0.5348]])


In [54]:
attention_weights = torch.softmax(scores, dim=-1)
print(attention_weights)

tensor([[0.2877, 0.3025, 0.1716, 0.2383],
        [0.1194, 0.3905, 0.0808, 0.4092],
        [0.2284, 0.4225, 0.0760, 0.2730],
        [0.1415, 0.3857, 0.0856, 0.3872]])


In [55]:
output = attention_weights @ V
print(output)
print(output.shape)

tensor([[-1.7574,  0.6233, -0.8510,  0.1773],
        [-2.0472,  0.4370, -0.8897,  0.4510],
        [-1.9347,  0.5356, -0.8861,  0.3699],
        [-2.0177,  0.4590, -0.8870,  0.4248]])
torch.Size([4, 4])


In [56]:
print(Q)
print(K)

tensor([[ 0.0720, -0.4231, -0.4145, -0.6696],
        [ 1.0125,  1.9437,  0.3270, -2.5346],
        [ 0.6743, -0.6149, -0.2315, -1.9754],
        [ 0.8100,  2.0572,  0.2310, -2.8414]])
tensor([[-9.0136e-03,  5.5828e-01,  1.0578e-01,  1.4955e+00],
        [ 1.9592e+00,  7.6636e-01, -1.8731e-03,  1.4925e+00],
        [-4.9610e-02,  1.2028e+00,  5.6781e-01,  2.3413e+00],
        [ 1.9981e+00,  1.1453e+00,  2.7520e-01,  1.7976e+00]])


In [57]:
print(Q[0])

print(K[0])

scores11 = Q[0] @ K[0]
scores12 = Q[0] @ K[1]
scores13 = Q[0] @ K[2]
scores14 = Q[0] @ K[3]

scores = torch.stack([
    scores11,
    scores12,
    scores13,
    scores14
])

print(scores.shape)

print(scores)

scores = scores/math.sqrt(d_k)

print(scores)

scores = torch.softmax(scores, dim=-1)

print(f"V = {V}")
print(scores)

scores = scores @ V
print("scores after @V")
print(scores)


tensor([ 0.0720, -0.4231, -0.4145, -0.6696])
tensor([-0.0090,  0.5583,  0.1058,  1.4955])
torch.Size([4])
tensor([-1.2821, -1.1818, -2.3156, -1.6584])
tensor([-0.6411, -0.5909, -1.1578, -0.8292])
V = tensor([[-1.1970,  1.2415, -0.8746, -0.3680],
        [-2.2652,  0.2825, -0.9229,  0.8382],
        [-1.0770,  0.6171, -0.5851, -0.5461],
        [-2.2790,  0.3140, -0.9225,  0.5175]])
tensor([0.2877, 0.3025, 0.1716, 0.2383])
scores after @V
tensor([-1.7574,  0.6233, -0.8510,  0.1773])


# multi headed self attention

In [58]:
seq_len = 4
d_model = 8
num_heads = 2

d_k = d_model // num_heads

X = torch.randn(seq_len, d_model)

print(f"x = {X.shape}")
print(f"d_k = {d_k}")

x = torch.Size([4, 8])
d_k = 4


In [59]:
W_Q = torch.randn(d_model, d_model) # d_k before splitting based on head is same as d_model, we progress which is better to make the model learn the parameters
W_K = torch.randn(d_model, d_model)
W_V = torch.randn(d_model, d_model)

Q = X @ W_Q

K = X @ W_K

V = X @ W_V

print(Q.shape)
print(K.shape)
print(V.shape)
print('\n')
print(Q)

torch.Size([4, 8])
torch.Size([4, 8])
torch.Size([4, 8])


tensor([[-2.5090,  0.5599,  5.1385,  1.1498,  2.1700, -0.9508, -0.8187, -1.2652],
        [-0.5434,  0.2169,  1.5733,  4.9437,  0.9145,  0.1673, -1.9814,  0.6744],
        [-6.0908, -0.5521, -1.9110,  2.2170,  0.5591,  1.5691,  3.3131, -0.3604],
        [-5.7809, -2.3053,  3.9936,  2.0768, -0.5484, -4.4979, -1.0524, -1.6200]])


In [60]:
Q = Q.view(seq_len, num_heads, d_k) # 4, 2, 4

print(Q)

Q = Q.transpose(0, 1)

print(Q.shape)

print('\n')

print(Q)


tensor([[[-2.5090,  0.5599,  5.1385,  1.1498],
         [ 2.1700, -0.9508, -0.8187, -1.2652]],

        [[-0.5434,  0.2169,  1.5733,  4.9437],
         [ 0.9145,  0.1673, -1.9814,  0.6744]],

        [[-6.0908, -0.5521, -1.9110,  2.2170],
         [ 0.5591,  1.5691,  3.3131, -0.3604]],

        [[-5.7809, -2.3053,  3.9936,  2.0768],
         [-0.5484, -4.4979, -1.0524, -1.6200]]])
torch.Size([2, 4, 4])


tensor([[[-2.5090,  0.5599,  5.1385,  1.1498],
         [-0.5434,  0.2169,  1.5733,  4.9437],
         [-6.0908, -0.5521, -1.9110,  2.2170],
         [-5.7809, -2.3053,  3.9936,  2.0768]],

        [[ 2.1700, -0.9508, -0.8187, -1.2652],
         [ 0.9145,  0.1673, -1.9814,  0.6744],
         [ 0.5591,  1.5691,  3.3131, -0.3604],
         [-0.5484, -4.4979, -1.0524, -1.6200]]])


In [61]:
K = K.view(seq_len, num_heads, d_k).transpose(0, 1)
V = V.view(seq_len, num_heads, d_k).transpose(0, 1)

print(K.shape)
print(V.shape)

torch.Size([2, 4, 4])
torch.Size([2, 4, 4])


In [62]:
scores = Q @ K.transpose(-2, -1)
print(scores.shape)

torch.Size([2, 4, 4])


In [63]:
scores = scores / math.sqrt(d_k)

attention_weights = torch.softmax(scores, -1)

output = attention_weights @ V

print(output.shape)

W_O = torch.randn(d_model, d_model)

print(W_O)



torch.Size([2, 4, 4])
tensor([[-1.3793,  0.6258, -2.5850, -0.0240, -0.1222, -0.7470,  1.7093,  0.0579],
        [ 1.1930,  1.9373,  0.7287,  0.9809,  0.4146,  1.1566,  0.2691, -0.0366],
        [ 0.9733, -1.0151, -0.5419, -0.4410, -0.3136, -0.1293, -0.7150, -0.0476],
        [ 2.0207,  0.2539,  0.9364,  0.7122, -0.0318,  0.1016,  1.3433,  0.7133],
        [ 0.4038, -0.7140,  0.8337, -0.9585,  0.4536,  1.2461, -2.3065, -1.2869],
        [ 0.1799, -2.1268, -0.1341, -1.0408, -0.7647, -0.0553,  1.2049, -0.9825],
        [ 0.4334, -0.7172,  1.0554, -1.4534,  0.4652,  0.3714, -0.0047,  0.0795],
        [ 0.3782,  0.7051, -1.7237, -0.8435,  0.4351,  0.2659, -0.5871,  0.0827]])


In [67]:
head_outputs = output.transpose(0, 1)

print(head_outputs.shape)

head_output = head_outputs.reshape(seq_len, d_model) # 4, 8

print(head_output.shape)

print(W_O.shape)

output = head_output @ W_O

print(output.shape)

torch.Size([4, 2, 4])
torch.Size([4, 8])
torch.Size([8, 8])
torch.Size([4, 8])
